name: Juice Shop Security Fuzzing

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  security-fuzzing:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - name: Clone and setup Juice Shop
      run: |
        git clone https://github.com/juice-shop/juice-shop.git
        cd juice-shop
        npm install --production
    
    - name: Start Juice Shop
      run: |
        cd juice-shop
        npm start &
        sleep 45
        curl -f http://localhost:3000 || echo "Juice Shop may not be ready"
    
    - name: Install ffuf
      run: |
        wget https://github.com/ffuf/ffuf/releases/download/v2.1.0/ffuf_2.1.0_linux_amd64.tar.gz
        tar -xzf ffuf_2.1.0_linux_amd64.tar.gz
        chmod +x ffuf
        sudo mv ffuf /usr/local/bin/
        ffuf -version
    
    - name: Run Python fuzzing script
      run: |
        python fuzz_script.py http://localhost:3000
      continue-on-error: true
    
    - name: Run ffuf fuzzing
      run: |
        echo '{"email":"FUZZ","password":"test123"}' > request_template.json
        ffuf -w sql_payloads.txt:FUZZ -u http://localhost:3000/rest/user/login -X POST -H "Content-Type: application/json" -d @request_template.json -mc all -o ffuf_results.json -of json -t 1 -p 0.5
      continue-on-error: true
    
    - name: Show results
      run: |
        echo "=== RESULTS ==="
        ls -la *.json || echo "No JSON files found"
        if [ -f "fuzz_results.json" ]; then
          echo "Python results found"
          head -20 fuzz_results.json
        fi
        if [ -f "ffuf_results.json" ]; then
          echo "ffuf results found"
          head -20 ffuf_results.json
        fi
    
    - name: Create report bundle
      run: |
        mkdir -p security-reports
        cp *.json security-reports/ 2>/dev/null || echo "No JSON files to copy"
        cp *.txt security-reports/ 2>/dev/null || echo "No TXT files to copy"
        echo "Fuzzing completed at $(date)" > security-reports/summary.txt
        tar -czf security-reports-bundle.tar.gz security-reports/
        ls -la security-reports/
    
    - name: Upload results
      uses: actions/upload-artifact@v4
      with:
        name: security-reports-bundle
        path: security-reports-bundle.tar.gz
        retention-days: 30
      if: always()
